name: dea
channels:
  - conda-forge
  - simpleitk
dependencies:
  - python=3.10
  - jupyterlab
  - nodejs
  - ipywidgets
  - pandas
  - dask
  - dask-image  
  - dask-labextension
  - zarr
  - numcodecs
  - scikit-image 
  - matplotlib
  - matplotlib-scalebar
  - seaborn
  - tqdm
  - openpyxl  
  - simpleitk
  - tabulate
