name: dea
channels:
  - simpleitk
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - nodejs
  - ipywidgets
  - pandas
  - dask
  - dask-image  
  - imageio
  - numpy
  - scipy  
  - scikit-image 
  - matplotlib
  - seaborn
  - tqdm
  - openpyxl  
  - simpleitk
