name: dea
channels:
  - conda-forge
  - simpleitk
dependencies:
  - python=3.10
  - jupyterlab
  - ipywidgets
  - pandas
  - dask
  - dask-image  
  - scikit-image 
  - matplotlib
  - seaborn
  - tqdm
  - openpyxl  
  - simpleitk
  - tabulate